title: Alex Nichols
tagline: Husband, father, and Program Manager at Microsoft
description: >- 
  A personal website for Alex Nichols, a husband, father, and Program Manager at Microsoft.
baseurl: ""
name: "alexcnichols.github.io"
url: "https://alexcnichols.github.io"
lang: en-US
author: 
  name: Alex Nichols
  twitter: alexcnichols
permalink: slug
twitter:
  username: alexcnichols
  card: summary
social:
  name: Alex Nichols
  links: 
    twitter: https://twitter.com/alexcnichols
    linkedin: https://linkedin.com/alexcnichols
    github: https://github.com/alexcnichols
google_analytics: UA-117848109-2
exclude: 
  - assets/default.css
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - package-lock.json
  - package.json
  - README.md
  - start.sh
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-octicons
strict_front_matter: true
